# Build matrix / environment variable are explained on:
# https://docs.travis-ci.com/user/customizing-the-build/
# This file can be validated on:
# http://lint.travis-ci.org/

language: cpp

# Define the matrix explicitly, manually expanding the combinations of (os, compiler, env).
# It is more tedious, but grants us far more flexibility.
matrix:
  include:
    - os: linux
      dist: xenial
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'deb https://apt.llvm.org/xenial/ llvm-toolchain-xenial-9 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - clang-9
      env:
        - CXX=clang++-9
        - CXXSTD=-std=c++17
        - CXXFLAGS=-stdlib=libc++
      install: ./ci/install-linux.sh && ./ci/log-config.sh
      script: ./ci/build-linux-bazel.sh

# # These are the install and build (script) phases for the most common entries in the matrix.  They could be included
# # in each entry in the matrix, but that is just repetitive.
# install:
#   - ./ci/install-${TRAVIS_OS_NAME}.sh
#   - . ./ci/env-${TRAVIS_OS_NAME}.sh
#   - ./ci/log-config.sh

# script: ./ci/travis.sh

# This section installs the necessary dependencies.
# addons:
#   apt:
#     packages:
#     - g++
#     - clang-9
#     update: true
#   # homebrew:
#   #   packages:
#   #   - ccache
#   #   - gcc@4.9
#   #   - llvm@4
#   #   update: true

# notifications:
#   email: false
